name: uuid-converter
static_sites:
- name: uuid-converter
  github:
    repo: jarin/uuidformat
    branch: main
  source_dir: /
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
    preserve_path_prefix: false